[package]
name = "twatch2020v3_rs"
version = "0.1.0"
authors = ["Placeless <thinkoverheat@gmail.com>"]
edition = "2024"
resolver = "2"
rust-version = "1.87"

[[bin]]
name = "twatch2020v3_rs"
harness = false # do not use the built in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
default = []
experimental = ["esp-idf-svc/experimental"]

[dependencies]
esp-idf-hal = "0.45"
embedded-graphics = "0.8"
mipidsi = "0.7"
st7789 = "0.7"
anyhow = "1.0"
esp-idf-svc = "0.51.0"

[build-dependencies]
embuild = "0.33"
