[package]
name = "twatch2020v3_rs"
version = "0.1.0"
authors = ["Placeless <thinkoverheat@gmail.com>"]
edition = "2024"
resolver = "2"
rust-version = "1.87"

[[bin]]
name = "twatch2020v3_rs"
harness = false # do not use the built in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
default = []
experimental = ["esp-idf-svc/experimental"]

[dependencies]
anyhow = "1.0.98"
log = "0.4.26"
esp-idf-svc = { version = "0.51", features = ["critical-section", "embassy-time-driver", "embassy-sync"] }
esp-idf-hal = "0.45.2"
esp-idf-sys = "0.36.1"
mipidsi = "0.9.0"
embedded-graphics-core = { version = "0.4.0" }
embedded-graphics = { version = "0.8.1" }
embedded-graphics-framebuf = "0.5.0"
# egui = "0.31.0"
display-interface-spi = { version = "0.5.0" }
chrono = "0.4"
# 別に full はいらない
tokio = { version = "1.43.0", features = ["rt", "macros"] }
async-std = { version = "1.13.0", features = ["attributes"] }
axp192 = "0.2.0"
embedded-hal = "1.0.0"

[build-dependencies]
embuild = "0.33"
