[package]
name = "twatch2020v3_rs"
version = "0.1.0"
authors = ["Placeless <mikoprpr@hotmail.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.84"

[[bin]]
name = "twatch2020v3_rs"
harness = false # do not use the built in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
default = ["std", "embassy", "esp-idf-svc/native"]
pio = ["esp-idf-svc/pio"]
std = ["alloc", "esp-idf-svc/binstart", "esp-idf-svc/std"]
alloc = ["esp-idf-svc/alloc"]
nightly = ["esp-idf-svc/nightly"]
experimental = ["esp-idf-svc/experimental"]
embassy = ["esp-idf-svc/embassy-sync", "esp-idf-svc/critical-section", "esp-idf-svc/embassy-time-driver"]

[dependencies]
log = "0.4"
esp-idf-svc = { version = "0.51", features = ["critical-section", "embassy-time-driver", "embassy-sync"] }
#下2桁ありの””なしはエラー
esp-idf-hal = "0.45.2"
esp-idf-sys = "0.36.1"
anyhow = {version = "1", features = ["backtrace"]}

[build-dependencies]
embuild = "0.33"
